# Generated by Django 4.1.7 on 2023-03-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_staff_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': (('can_view_staff', 'Can view staff'), ('can_edit_staff', 'Can edit staff'), ('can_delete_staff', 'Can delete staff'))},
        ),
    ]
