# Generated by Django 4.1.7 on 2023-04-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='timeline',
            field=models.CharField(default='6 days left', max_length=200, null=True),
        ),
    ]
