# Generated by Django 4.1.7 on 2023-03-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
