# Generated by Django 4.1.7 on 2023-03-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
    ]
