# Generated by Django 4.1.7 on 2023-03-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_staff_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='Date_Joined',
        ),
        migrations.AddField(
            model_name='staff',
            name='Status',
            field=models.TextField(default='Staff', verbose_name='Staff'),
        ),
    ]
