# Generated by Django 4.1.7 on 2023-03-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_staff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
    ]
