# Generated by Django 4.1.7 on 2023-03-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_product_digital_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
