# Generated by Django 4.1.7 on 2023-04-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inlist',
            field=models.BooleanField(default=False),
        ),
    ]
