# Generated by Django 4.1.7 on 2023-04-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_inlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
    ]
